site: Hayato Sumino Official Website

collections:
  pages:
    output: true
    permalink: /:name
  # concerts:
    # output: true
    # permalink: /concerts/:slug
  posts:
    output: true
    permalink: /concerts/:slug
  projects:
    output: true
    permalink: /info/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"


markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 6
# paginate_path: "/blog/page:num/"
paginate_path: "/concerts/page:num/"


# Google-analytics
google-analytics:
  id:               ""

# for seo
twitter:
  username: 880hz
facebook:
  app_id: hayato.sumino.7
  publisher: https://www.facebook.com/Hayato-Sumino-1108930259264225
logo: /img/logo.png
