# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.hayatosum.com
title: 角野隼斗 Hayato Sumino Official Website
lefttop: Hayato Sumino
email: hay88.sum10ms@gmail.com
author: Hayato Sumino
description: ピアニスト角野隼斗のオフィシャルホームページです。1995年生まれ。2018年、ピティナピアノコンペティション特級グランプリ、及び文部科学大臣賞、スタインウェイ賞受賞。現在、東京大学情報理工学系研究科修士1年生。
copyright: 'Copyright &copy; 2019 Hayato Sumino. All Rights Reserved.'
# credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/880hz
  - title: instagram
    url: https://www.instagram.com/8810hz/
  - title: youtube
    url: https://www.youtube.com/user/chopin8810

# ----------------------- #
#   Concerts              #
# ----------------------- #

concerts:
  - layout: default
    img: 20190219.png
    category: Concerts
    title: Hakujuベーゼンドルファー・サロンコンサートシリーズ ランチタイム・コンサート【完売】
    content: 日時：2月19日（火）12時開演<br>会場：<a href="https://www.hakujuhall.jp/access/index.html">白寿本社ビル１階（東京）</a><br> 料金：ランチチケット付2,500円　コンサートのみ1,500円<br> 曲目：ショパン：ピアノ・ソナタ 第2番 変ロ短調 Op.35 「葬送」 全楽章<br> スクリャービン：ピアノ・ソナタ　第5番 Op.53<br>他

  - layout: default
    img: 20190316.png
    category: Concerts
    title: YAMAHA Salon Concert in Osaka　特級グランプリ褒賞演奏会
    content: 日時：3月16日（土）14時開演<br>会場：<a href="https://jp.yamaha.com/sp/piano/dealers_showrooms/showrooms/gps_osaka/access/">ヤマハグランドピアノサロン大阪</a><br> 料金：無料（要予約）<br> 曲目：ベートーヴェン：ピアノ・ソナタ 第21番 ハ長調「ワルトシュタイン」 Op.53<br>ショパン：ポロネーズ第6番　変イ長調　Op.53<br>スクリャービン：ピアノ・ソナタ 第5番 Op.53 他

  - layout: default
    img: 20190317.png
    category: Concerts
    title: YAMAHA Salon Concert in Nagoya　特級グランプリ褒賞演奏会【完売】
    content: 日時：3月17日（日）14時開演<br>会場：<a href="https://jp.yamaha.com/sp/piano/dealers_showrooms/showrooms/gps_nagoya/access/">ヤマハグランドピアノサロン名古屋</a><br> 料金：無料（要予約）<br> 曲目：ドビュッシー:喜びの島<br>フォーレ:ノクターン 第6番 Op.63 変ニ長調<br>ショパン：ピアノソナタ第2番 変ロ短調 Op.35 他

  - layout: default
    img: 20190320.png
    category: Concerts
    title: アグネスホール ランチタイムコンサート
    content: 日時：3月20日（水）12時半開演<br>会場：<a href="https://www.agneshotel.com/access/">アグネスホテル東京B1F アグネスホール</a><br> 料金：無料（予約不要）<br> 曲目：カプースチン：フルート、チェロとピアノのための三重奏曲他

  - layout: default
    img: 20190324.png
    category: Concerts
    title: <a href="http://www.piano.or.jp/concert/yp/">第42回ピティナ・ピアノコンペティション入賞者記念コンサート</a>
    content: 日時：3月24日（日）13時開演<br>会場：第一生命ホール<br>料金：一般3,500円 ピティナ会員・学生3,000円<br>曲目：カプースチン：フルート、チェロとピアノのための三重奏曲<br>リスト :死の舞踏（サン=サーンス） S.555 R.240
