# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.hayatosum.com
title: 角野隼斗 - Hayato Sumino
lefttop: Hayato Sumino
email: hay88.sum10ms@gmail.com
author: Hayato Sumino
description: これはピアニスト角野隼斗のホームページです。
copyright: 'Copyright &copy; 2019 Hayato Sumino. All Rights Reserved.'
# credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/880hz
  - title: instagram
    url: https://www.instagram.com/8810hz/
  - title: youtube
    url: https://www.youtube.com/user/chopin8810

concerts:
  - layout: default
    img: 20190219.png
    category: Concerts
    title: Hakujuベーゼンドルファー・サロンコンサートシリーズ ランチタイム・コンサート　角野隼斗【完売】
    content: 会場：白寿本社ビル１階（東京）、<br> 料金：ランチチケット付2,500円　コンサートのみ1,500円、<br> 曲目：ショパン：ピアノ・ソナタ 第2番 変ロ短調 Op.35 「葬送」 全楽章<br> スクリャービン：ピアノ・ソナタ　第5番 Op.53<br>他
